export const thumbnails = {
    'FCB'  : require('../../assets/FCB.jpg'),
    'LAC'    : require('../../assets/LAC.jpg'),
    'ATM'    : require('../../assets/ATM.jpg'),
    'BET'    : require('../../assets/BET.jpg'),
    'BIL'    : require('../../assets/BIL.jpg'),
    'EIB'    : require('../../assets/EIB.jpg'),
    'ESP'    : require('../../assets/ESP.jpg'),
    'FCG'    : require('../../assets/FCG.jpg'),
    'GCF'    : require('../../assets/GCF.jpg'),
    'LPA'    : require('../../assets/LPA.jpg'),
    'LUD'    : require('../../assets/LUD.jpg'),
    'MAD'    : require('../../assets/MAD.jpg'),
    'MAL'    : require('../../assets/MAL.jpg'),
    'RSS'    : require('../../assets/RSS.jpg'),
    'SEV'    : require('../../assets/SEV.jpg'),
    'SPO'    : require('../../assets/SPO.jpg'),
    'VAL'    : require('../../assets/VAL.jpg'),
    'VALL'    : require('../../assets/VALL.jpg'),
    'VCF'    : require('../../assets/VCF.jpg'),
    'VIG'    : require('../../assets/VIG.jpg'),
  }